name: Deploy to GitHub Pages V2

permissions:
  contents: write

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Define the "build" job
  build:
    # Add a dependency to the "test" job
    needs: [lint, test]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Compile and build the project
      - name: Build project
        run: |
          npm run build

      # Step 5: Upload the dist folder as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  # Define the "deploy" job
  deploy:
    # Add a dependency to the "build" job
    needs: build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (Usually not required if not deploying to gh-pages)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Download the artifact from the build job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: "dist/"

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: "dist/"

  # Define the "test" job
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Compile and build the project
      - name: Test project
        run: |
          npm run test

  # Define the "test" job
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Compile and build the project
      - name: Test project
        run: |
          npm run lint
    
    # Don't fail the job if linting fails
    continue-on-error: true